# Generated by Django 4.2.3 on 2023-08-12 06:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kami', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycources',
            name='cource',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mycources',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mycources',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mycources',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kami.mypage'),
        ),
    ]
