# Generated by Django 4.2.3 on 2023-08-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kami', '0003_rename_mycources_mycourses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycourses',
            name='playlist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mycourses',
            name='video_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
