# Generated by Django 4.2.3 on 2023-08-12 14:01

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kami', '0005_mycourses_image_mypage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
