# Generated by Django 4.2.3 on 2023-08-12 15:07

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kami', '0006_interest_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFF00', image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='info',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kami.mypage'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFF00', image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
