# Generated by Django 4.2.3 on 2023-08-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kami', '0007_skill_color_alter_info_user_alter_interest_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='icon_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
