# Generated by Django 4.2.3 on 2023-08-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kami', '0009_resume_moreresume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='education',
        ),
        migrations.AddField(
            model_name='resume',
            name='choice',
            field=models.CharField(blank=True, choices=[('Education', 'Education'), ('Exprience', 'Exprience')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
