# Generated by Django 4.2.3 on 2023-08-12 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kami', '0010_remove_resume_education_resume_choice_resume_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoreResume',
            new_name='More',
        ),
    ]
