# Generated by Django 4.2.3 on 2023-08-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kami', '0011_rename_moreresume_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mypage',
            old_name='email_id',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='mypage',
            old_name='mobile_no',
            new_name='mobile',
        ),
        migrations.AlterField(
            model_name='resume',
            name='choice',
            field=models.CharField(blank=True, choices=[('Education', 'Education'), ('Experience', 'Experience')], max_length=200, null=True),
        ),
    ]
