# Generated by Django 4.2.3 on 2023-08-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kami', '0013_tag_blog_mycourses_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='img/blogs/'),
        ),
    ]
